apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: backend
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=192.168.44.44:8082/docker-local/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: backend
    repoURL: 'https://github.com/zax75ster/Argo_CD.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false